name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js latest
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Build and Deploy
      run: npm run build && npm run deploy
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: steps.deploy.outputs.branch == 'main'
